[package]
name = "venv-clean"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
fs_extra = "1.3.0"
num-format = "0.4.4"

[dev-dependencies]
tempfile = "3.10.1"
